In [1]:
import pandas as pd

In [35]:
no_execution_stream = '../log/rmsc03_demo_no_100_20200605/EXCHANGE_AGENT.bz2'
no_execution_ob = '../log/rmsc03_demo_no_100_20200605/ORDERBOOK_ABM_FULL.bz2'
yes_execution_stream = '../log/rmsc03_demo_yes_100_pov_0.01_20200605/EXCHANGE_AGENT.bz2'
yes_execution_ob = '../log/rmsc03_demo_yes_100_pov_0.01_20200605/ORDERBOOK_ABM_FULL.bz2'

In [36]:
no_execution_stream_df = pd.read_pickle(no_execution_stream)
yes_execution_stream_df = pd.read_pickle(yes_execution_stream)
no_execution_ob_df = pd.read_pickle(no_execution_ob)
yes_execution_ob_df = pd.read_pickle(yes_execution_ob)

In [37]:
no_execution_stream_df

                                    EventType          Event
EventTime
NaT                                AGENT_TYPE  ExchangeAgent
2020-06-05 00:00:00.000000777   WHEN_MKT_OPEN            212
2020-06-05 00:00:00.000000777  WHEN_MKT_CLOSE            212
2020-06-05 00:00:00.000002550   WHEN_MKT_OPEN           4552
2020-06-05 00:00:00.000002550  WHEN_MKT_CLOSE           4552
...                                       ...            ...
2020-06-05 11:30:40.170050542    QUERY_SPREAD           5050
2020-06-05 11:30:41.038033305    QUERY_SPREAD           5015
2020-06-05 11:30:43.105505869    QUERY_SPREAD           5058
2020-06-05 11:30:43.305320434    QUERY_SPREAD           5031
2020-06-05 11:30:56.987227858    QUERY_SPREAD           1922

[637534 rows x 2 columns]

In [38]:
yes_execution_stream_df

                                    EventType          Event
EventTime
NaT                                AGENT_TYPE  ExchangeAgent
2020-06-05 00:00:00.000000777   WHEN_MKT_OPEN            212
2020-06-05 00:00:00.000000777  WHEN_MKT_CLOSE            212
2020-06-05 00:00:00.000002550   WHEN_MKT_OPEN           4552
2020-06-05 00:00:00.000002550  WHEN_MKT_CLOSE           4552
...                                       ...            ...
2020-06-05 11:30:40.170050542    QUERY_SPREAD           5050
2020-06-05 11:30:41.038033305    QUERY_SPREAD           5015
2020-06-05 11:30:43.105505869    QUERY_SPREAD           5058
2020-06-05 11:30:43.305320434    QUERY_SPREAD           5031
2020-06-05 11:30:56.987227858    QUERY_SPREAD           1922

[637534 rows x 2 columns]

In [39]:
stream_equality = no_execution_stream_df.reset_index().eq(yes_execution_stream_df.reset_index())
ob_equality = no_execution_ob_df.reset_index().eq(yes_execution_ob_df.reset_index())

In [40]:
for row in stream_equality.iterrows():
    idx = row[0]
    cols_equal = row[1].all()
    if not cols_equal:
        print(f"Row unequal: {idx}")

Row unequal: 0

differences start at `41355`

In [41]:
no_execution_stream_df.iloc[41353:41375]

                                  EventType          Event
EventTime
2020-06-05 09:30:59.947141285      BEST_BID  ABM,99980,119
2020-06-05 09:30:59.947141285      BEST_ASK  ABM,99981,129
2020-06-05 09:31:00.002461725  QUERY_SPREAD           5118
2020-06-05 09:31:00.002534259  QUERY_SPREAD           5124
2020-06-05 09:31:00.002969166  QUERY_SPREAD           5105
2020-06-05 09:31:00.003118641  QUERY_SPREAD           5122
2020-06-05 09:31:00.003161037  QUERY_SPREAD           5114
2020-06-05 09:31:00.005743971  QUERY_SPREAD           5108
2020-06-05 09:31:00.008671332  QUERY_SPREAD           5106
2020-06-05 09:31:00.009633639  QUERY_SPREAD           5127
2020-06-05 09:31:00.011369259  QUERY_SPREAD           5119
2020-06-05 09:31:00.012011514  QUERY_SPREAD           5121
2020-06-05 09:31:00.012634749  QUERY_SPREAD           5120
2020-06-05 09:31:00.013053903  QUERY_SPREAD           5115
2020-06-05 09:31:00.014540973  QUERY_SPREAD           5110
2020-06-05 09:31:00.014633445  QUERY_SPREAD           5112
2020-06-05 09:31:00.014650707  QUERY_SPREAD           5113
2020-06-05 09:31:00.014792703  QUERY_SPREAD           5126
2020-06-05 09:31:00.016120989  QUERY_SPREAD           5111
2020-06-05 09:31:00.016572123  QUERY_SPREAD           5116
2020-06-05 09:31:00.016839924  QUERY_SPREAD           5123
2020-06-05 09:31:00.017671488  QUERY_SPREAD           5103

In [42]:
yes_execution_stream_df.iloc[41353:41375]

                                  EventType          Event
EventTime
2020-06-05 09:30:59.947141285      BEST_BID  ABM,99980,119
2020-06-05 09:30:59.947141285      BEST_ASK  ABM,99981,129
2020-06-05 09:31:00.002461725  QUERY_SPREAD           5118
2020-06-05 09:31:00.002534259  QUERY_SPREAD           5124
2020-06-05 09:31:00.002969166  QUERY_SPREAD           5105
2020-06-05 09:31:00.003118641  QUERY_SPREAD           5122
2020-06-05 09:31:00.003161037  QUERY_SPREAD           5114
2020-06-05 09:31:00.005743971  QUERY_SPREAD           5108
2020-06-05 09:31:00.008671332  QUERY_SPREAD           5106
2020-06-05 09:31:00.009633639  QUERY_SPREAD           5127
2020-06-05 09:31:00.011369259  QUERY_SPREAD           5119
2020-06-05 09:31:00.012011514  QUERY_SPREAD           5121
2020-06-05 09:31:00.012634749  QUERY_SPREAD           5120
2020-06-05 09:31:00.013053903  QUERY_SPREAD           5115
2020-06-05 09:31:00.014540973  QUERY_SPREAD           5110
2020-06-05 09:31:00.014633445  QUERY_SPREAD           5112
2020-06-05 09:31:00.014650707  QUERY_SPREAD           5113
2020-06-05 09:31:00.014792703  QUERY_SPREAD           5126
2020-06-05 09:31:00.016120989  QUERY_SPREAD           5111
2020-06-05 09:31:00.016572123  QUERY_SPREAD           5116
2020-06-05 09:31:00.016839924  QUERY_SPREAD           5123
2020-06-05 09:31:00.017671488  QUERY_SPREAD           5103

In [43]:
no_execution_stream_df.iloc[41320:41350]

,EventType,Event
EventTime,,
2020-06-05 09:30:59.373432476,BEST_ASK,"ABM,99982,41"
2020-06-05 09:30:59.373432476,LAST_TRADE,"48,$99981.0000"
2020-06-05 09:30:59.530245407,QUERY_SPREAD,5032
2020-06-05 09:30:59.533026861,LIMIT_ORDER,"{'agent_id': 5032, 'time_placed': '2020-06-05T..."
2020-06-05 09:30:59.533026861,ORDER_EXECUTED,"{'agent_id': 5032, 'time_placed': '2020-06-05T..."
2020-06-05 09:30:59.533026861,ORDER_EXECUTED,"{'agent_id': 5043, 'time_placed': '2020-06-05T..."
2020-06-05 09:30:59.533026861,ORDER_ACCEPTED,"{'agent_id': 5032, 'time_placed': '2020-06-05T..."
2020-06-05 09:30:59.533026861,BEST_BID,"ABM,99980,27"
2020-06-05 09:30:59.533026861,BEST_ASK,"ABM,99981,33"
2020-06-05 09:30:59.533026861,LAST_TRADE,"6,$99981.0000"
2020-06-05 09:30:59.606215513,QUERY_SPREAD,5023
2020-06-05 09:30:59.610115466,LIMIT_ORDER,"{'agent_id': 5023, 'time_placed': '2020-06-05T..."
2020-06-05 09:30:59.610115466,ORDER_ACCEPTED,"{'agent_id': 5023, 'time_placed': '2020-06-05T..."
2020-06-05 09:30:59.610115466,BEST_BID,"ABM,99980,52"
2020-06-05 09:30:59.610115466,BEST_ASK,"ABM,99981,33"
2020-06-05 09:30:59.670681591,QUERY_SPREAD,5082
2020-06-05 09:30:59.672671143,LIMIT_ORDER,"{'agent_id': 5082, 'time_placed': '2020-06-05T..."
2020-06-05 09:30:59.672671143,ORDER_ACCEPTED,"{'agent_id': 5082, 'time_placed': '2020-06-05T..."
2020-06-05 09:30:59.672671143,BEST_BID,"ABM,99980,94"
2020-06-05 09:30:59.672671143,BEST_ASK,"ABM,99981,33"
2020-06-05 09:30:59.813292997,QUERY_SPREAD,5056
2020-06-05 09:30:59.814920497,LIMIT_ORDER,"{'agent_id': 5056, 'time_placed': '2020-06-05T..."
2020-06-05 09:30:59.814920497,ORDER_ACCEPTED,"{'agent_id': 5056, 'time_placed': '2020-06-05T..."
2020-06-05 09:30:59.814920497,BEST_BID,"ABM,99980,94"
2020-06-05 09:30:59.814920497,BEST_ASK,"ABM,99981,82"
2020-06-05 09:30:59.897167470,QUERY_SPREAD,5090
2020-06-05 09:30:59.900761714,LIMIT_ORDER,"{'agent_id': 5090, 'time_placed': '2020-06-05T..."
2020-06-05 09:30:59.900761714,ORDER_ACCEPTED,"{'agent_id': 5090, 'time_placed': '2020-06-05T..."
2020-06-05 09:30:59.900761714,BEST_BID,"ABM,99980,119"
2020-06-05 09:30:59.900761714,BEST_ASK,"ABM,99981,82"

In [44]:
yes_execution_stream_df.iloc[41320:41350]

,EventType,Event
EventTime,,
2020-06-05 09:30:59.373432476,BEST_ASK,"ABM,99982,41"
2020-06-05 09:30:59.373432476,LAST_TRADE,"48,$99981.0000"
2020-06-05 09:30:59.530245407,QUERY_SPREAD,5032
2020-06-05 09:30:59.533026861,LIMIT_ORDER,"{'agent_id': 5032, 'time_placed': '2020-06-05T..."
2020-06-05 09:30:59.533026861,ORDER_EXECUTED,"{'agent_id': 5032, 'time_placed': '2020-06-05T..."
2020-06-05 09:30:59.533026861,ORDER_EXECUTED,"{'agent_id': 5043, 'time_placed': '2020-06-05T..."
2020-06-05 09:30:59.533026861,ORDER_ACCEPTED,"{'agent_id': 5032, 'time_placed': '2020-06-05T..."
2020-06-05 09:30:59.533026861,BEST_BID,"ABM,99980,27"
2020-06-05 09:30:59.533026861,BEST_ASK,"ABM,99981,33"
2020-06-05 09:30:59.533026861,LAST_TRADE,"6,$99981.0000"
2020-06-05 09:30:59.606215513,QUERY_SPREAD,5023
2020-06-05 09:30:59.610115466,LIMIT_ORDER,"{'agent_id': 5023, 'time_placed': '2020-06-05T..."
2020-06-05 09:30:59.610115466,ORDER_ACCEPTED,"{'agent_id': 5023, 'time_placed': '2020-06-05T..."
2020-06-05 09:30:59.610115466,BEST_BID,"ABM,99980,52"
2020-06-05 09:30:59.610115466,BEST_ASK,"ABM,99981,33"
2020-06-05 09:30:59.670681591,QUERY_SPREAD,5082
2020-06-05 09:30:59.672671143,LIMIT_ORDER,"{'agent_id': 5082, 'time_placed': '2020-06-05T..."
2020-06-05 09:30:59.672671143,ORDER_ACCEPTED,"{'agent_id': 5082, 'time_placed': '2020-06-05T..."
2020-06-05 09:30:59.672671143,BEST_BID,"ABM,99980,94"
2020-06-05 09:30:59.672671143,BEST_ASK,"ABM,99981,33"
2020-06-05 09:30:59.813292997,QUERY_SPREAD,5056
2020-06-05 09:30:59.814920497,LIMIT_ORDER,"{'agent_id': 5056, 'time_placed': '2020-06-05T..."
2020-06-05 09:30:59.814920497,ORDER_ACCEPTED,"{'agent_id': 5056, 'time_placed': '2020-06-05T..."
2020-06-05 09:30:59.814920497,BEST_BID,"ABM,99980,94"
2020-06-05 09:30:59.814920497,BEST_ASK,"ABM,99981,82"
2020-06-05 09:30:59.897167470,QUERY_SPREAD,5090
2020-06-05 09:30:59.900761714,LIMIT_ORDER,"{'agent_id': 5090, 'time_placed': '2020-06-05T..."
2020-06-05 09:30:59.900761714,ORDER_ACCEPTED,"{'agent_id': 5090, 'time_placed': '2020-06-05T..."
2020-06-05 09:30:59.900761714,BEST_BID,"ABM,99980,119"
2020-06-05 09:30:59.900761714,BEST_ASK,"ABM,99981,82"